
#ifndef __APP_WINDOW_STOPWATCH_LAYOUT_H__
#define __APP_WINDOW_STOPWATCH_LAYOUT_H__

#include "feature_all.h"
#include "gui_core_all.h"

typedef enum
{
	STOPWATCH_TIME_ID_TEXT = 100,
	STOPWATCH_TIME_ID_RESET_RECORD,
	STOPWATCH_TIME_ID_START,
	STOPWATCH_TIME_ID_TIME,
	STOPWATCH_TIME_ID_NAME,
	STOPWATCH_TIME_ID_RECORD_TEXT, //
	STOPWATCH_TIME_ID_RECORD_RECT,
	STOPWATCH_TIME_ID_RECORD_TIME,
	STOPWATCH_TIME_ID_RECORD_NAME,
}APP_WINDOW_STOPWATCH_LAYOUT_ID;


extern const gui_screen_struct gui_screen_stopwatch;


#endif

