#ifndef __APP_WINDOW_SOUND_TOUCH_LAYOUT_H__
#define __APP_WINDOW_SOUND_TOUCH_LAYOUT_H__

#include "feature_all.h"
#include "gui_core_all.h"

typedef enum
{
	SOUND_TOUCH_LAYOUT_ID_NONE = 100,

	SOUND_TOUCH_LAYOUT_ID_SOUND,
	SOUND_TOUCH_LAYOUT_ID_SOUND_PROGRESS,

	SOUND_TOUCH_LAYOUT_ID_TOUCH,
	SOUND_TOUCH_LAYOUT_ID_TOUCH_OPEN,
	
	SOUND_TOUCH_LAYOUT_ID_TEXT_1,
	SOUND_TOUCH_LAYOUT_ID_TEXT_1_GRAY,
	SOUND_TOUCH_LAYOUT_ID_CHECKED_1,

	SOUND_TOUCH_LAYOUT_ID_TEXT_2,
	SOUND_TOUCH_LAYOUT_ID_TEXT_2_GRAY,
	SOUND_TOUCH_LAYOUT_ID_CHECKED_2,
};

extern const gui_screen_struct gui_screen_sound_touch;

#endif
