#ifndef __APP_WINDOW_SPORT_DATA_LAYOUT_H__
#define __APP_WINDOW_SPORT_DATA_LAYOUT_H__

#include "feature_all.h"
#include "gui_core_all.h"


typedef enum
{
	SPORT_DATA_LAYOUT_ID_NONE = 0,
	SPORT_DATA_LAYOUT_ID_BG,
	SPORT_DATA_LAYOUT_ID_RESET,
	SPORT_DATA_LAYOUT_ID_STOP,
	SPORT_DATA_LAYOUT_ID_TIME,
	SPORT_DATA_LAYOUT_ID_TIMES,
	SPORT_DATA_LAYOUT_ID_SWIM_LINE,
	SPORT_DATA_LAYOUT_ID_STEPS_LINE,


	SPORT_DATA_LAYOUT_ID_BPM_TEXT,
	SPORT_DATA_LAYOUT_ID_KCAL_TEXT,
	SPORT_DATA_LAYOUT_ID_BPM,
	SPORT_DATA_LAYOUT_ID_KCAL,
	SPORT_DATA_ID_BPM,
	SPORT_DATA_ID_KCAL,
	SPORT_DATA_LAYOUT_ID_FOOTBALL_BASE = 30,

	SPORT_DATA_ID_STEPS,
	SPORT_DATA_LAYOUT_ID_STEPS,
	SPORT_DATA_LAYOUT_ID_STEPS_TEXT,
	SPORT_DATA_LAYOUT_ID_SWIM_BASE = 60,

	SPORT_DATA_ID_KM,
	SPORT_DATA_LAYOUT_ID_KM,
	SPORT_DATA_LAYOUT_ID_KM_TEXT,


	SPORT_DATA_LAYOUT_ID_PAUSE_BASE = 100,
	SPORT_DATA_LAYOUT_ID_PAUSE_EXIT_TXT,
	SPORT_DATA_LAYOUT_ID_PAUSE_CONTINUE_TXT,
	SPORT_DATA_LAYOUT_ID_PAUSE_FINISH_TXT,
	SPORT_DATA_LAYOUT_ID_PAUSE_EXIT_PIC,
    SPORT_DATA_LAYOUT_ID_PAUSE_CONTINUE_PIC,

	SPORT_DATA_LAYOUT_ID_READY_BASE = 150,
	SPORT_DATA_LAYOUT_ID_READY_NUMBER,






}APP_WINDOW_SPORT_DATA_LAYOUT_ID;



extern const gui_screen_struct gui_screen_sport_data;


#endif

