#ifndef __APP_WINDOW_APPSPORT_LAYOUT_H__
#define __APP_WINDOW_APPSPORT_LAYOUT_H__

#include "feature_all.h"
#include "gui_core_all.h"


extern const gui_screen_struct gui_screen_appsport;

enum
{
	APPSPORT_DATA_LAYOUT_ID_TITLE,
	APPSPORT_DATA_LAYOUT_ID_LINES,
	APPSPORT_DATA_LAYOUT_ID_TIME,
	APPSPORT_DATA_LAYOUT_ID_BPM_TEXT,
	APPSPORT_DATA_LAYOUT_ID_KM_TEXT,

    APPSPORT_DATA_LAYOUT_ID_PAUSE_BASE = 100,
    APPSPORT_DATA_LAYOUT_ID_PAUSE_EXIT_TXT,
    APPSPORT_DATA_LAYOUT_ID_PAUSE_CONTINUE_TXT,
    APPSPORT_DATA_LAYOUT_ID_PAUSE_FINISH_TXT,
    APPSPORT_DATA_LAYOUT_ID_PAUSE_EXIT_PIC,
    APPSPORT_DATA_LAYOUT_ID_PAUSE_CONTINUE_PIC,
};


#endif

