#ifndef __GUI_CORE_TYPE_H__
#define __GUI_CORE_TYPE_H__

typedef enum
{
    GUI_RET_OK,
    GUI_RET_ERROR,
    GUI_RET_DONT_CARE,
}GUI_RET;

///////////////////////////////////////////////////////////////////////////
// GUI: Charts
enum{
    CHARTS_STYLE_BAR,
    CHARTS_STYLE_H_BAR,            // horizontal
    CHARTS_STYLE_LINE,
    CHARTS_STYLE_LINE_AND_FILL,
    };

enum{
    CHARTS_FLG_NONE,
    CHARTS_FLG_SHOW_XAXIS = 0x0001,
    CHARTS_FLG_SHOW_YAXIS = 0x0002,
    CHARTS_FLG_SHOW_AXIS  = 0x0003,
    
    CHARTS_FLG_SHOW_XLABEL = 0x0004,
    CHARTS_FLG_SHOW_YLABEL = 0x0008,
    CHARTS_FLG_SHOW_LABELS = 0x000C,

    CHARTS_FLG_RIGHT_YLABEL = 0x0010,
    CHARTS_FLG_TOP_XLABEL   = 0x0020,

    CHARTS_FLG_FIXED_XAXIS = 0x0100,
    CHARTS_FLG_FIXED_YAXIS = 0x0200,
    CHARTS_FLG_FIXED_AXIS  = 0x0300,

    CHARTS_FLG_SHOW_XGRID = 0x1000,
    CHARTS_FLG_SHOW_YGRID = 0x2000,
    CHARTS_FLG_SHOW_GRID  = 0x3000,
    
    CHARTS_FLG_INITED = 0x8000,
    };


///////////////////////////////////////////////////////////////////////////
/*
**UI界面排版的元素(共3个大类):
**图片,文字,绘图
*/
typedef enum {
	TYPE_GUI_DRAW_NONE = 0,		//不需要渲染
	
    TYPE_GUI_DRAW_PICTURE,		//图片
    TYPE_GUI_DRAW_TEXT,			//文字

	TYPE_GUI_DRAW_PICTURE_BOX,	//图片
    TYPE_GUI_DRAW_TEXT_BOX,		//文字框节点，不需要渲染
    TYPE_GUI_DRAW_PICTURE_9SCLICE,

    TYPE_GUI_DRAW_POINTER,          // 指针
    TYPE_GUI_DRAW_POINTER_1IMAGES,      // 1 pics, rotate
	TYPE_GUI_DRAW_POINTER_8IMAGES,   	// 8 pics
    TYPE_GUI_DRAW_POINTER_16IMAGES,  	// 16 pics
    TYPE_GUI_DRAW_POINTER_LINE_60, 	// 60 dec
    TYPE_GUI_DRAW_POINTER_LINE_360,    // 360 dec

	TYPE_GUI_DRAW_SHAPE_CUSTOM,		//自由绘图
    TYPE_GUI_DRAW_SHAPE_START,		//绘图
    TYPE_GUI_DRAW_SHAPE_POINT,
	TYPE_GUI_DRAW_SHAPE_LINE,
    TYPE_GUI_DRAW_SHAPE_STYLE_LINE,
    TYPE_GUI_DRAW_SHAPE_RECT,
    TYPE_GUI_DRAW_SHAPE_RECT_FILL,
    TYPE_GUI_DRAW_SHAPE_CIRCLE,
    TYPE_GUI_DRAW_SHAPE_CIRCLE_FILL,
    TYPE_GUI_DRAW_SHAPE_ARC,		//弧
    TYPE_GUI_DRAW_SHAPE_ARC_FILL,   // Pie
    TYPE_GUI_DRAW_SHAPE_POLYGON,
    TYPE_GUI_DRAW_SHAPE_POLYGON_FILL,
    TYPE_GUI_DRAW_SHAPE_END,

    TYPE_GUI_DRAW_DLWF_PICTURE,     // download watchface image.
    TYPE_GUI_DRAW_DLWF_SHAPE,

	TYPE_GUI_DRAW_QR_CODE,			//二维码
    TYPE_GUI_DRAW_BAR_CODE_128,			//条形码
	TYPE_GUI_DRAW_PARTICLE,			//粒子
	
    
} TYPE_GUI_DRAW;


/*
**UI界面的控件
*/
typedef enum {

	TYPE_GUI_CONTROL_NONE = 0,
	
//--------------基础控件开始-------------------------------
    TYPE_GUI_CONTROL_IMAGE,			//图片框
    TYPE_GUI_CONTROL_LABEL,			//文字框
    TYPE_GUI_CONTROL_CANVAS,		//画布
    TYPE_GUI_CONTROL_TEXTBOX,			//文本框
    TYPE_GUI_CONTROL_POINTER,           // 指针
	TYPE_GUI_CONTROL_LAYOUT_ITEM,		//组合里的子控件: 列表,页,表格等，混合组合
	TYPE_GUI_CONTROL_LAYOUT_CELL,		//组合里的子控件: 蜂窝子项      (块状，单图片)
	TYPE_GUI_CONTROL_IMAGE_LIST,		//多图组合
	TYPE_GUI_CONTROL_IMAGE_NUMBER,		//数字图片
	TYPE_GUI_CONTROL_IMAGE_PROGRESS,	//进度条图片
	TYPE_GUI_CONTROL_LINEAR_HORIZONTAL, // 多个控件水平线性排列
	TYPE_GUI_CONTROL_LINEAR_VERTICAL, 	// 多个控件垂直线性排列
	TYPE_GUI_CONTROL_PROGRESS_BAR,		// 进度条图片
	TYPE_GUI_CONTROL_QR_CODE,			//二维码
	TYPE_GUI_CONTROL_BAR_CODE_128C,			//条形码
	TYPE_GUI_CONTROL_PARTICLE,			//粒子

//--------------基础控件结束--------------------------------
	TYPE_GUI_CONTROL_START,
	TYPE_GUI_CONTROL_DATE,
	TYPE_GUI_CONTROL_TIME,
    TYPE_GUI_CONTROL_BT_ICON,
    TYPE_GUI_CONTROL_ANIMATION,
    TYPE_GUI_CONTROL_BATT_ICON,
    TYPE_GUI_CONTROL_BATT_LABEL,
    TYPE_GUI_CONTROL_SWITCH,
    TYPE_GUI_CONTROL_RING,
    TYPE_GUI_CONTROL_CHART,
    TYPE_GUI_CONTROL_SCROLL_TEXT,
	TYPE_GUI_CONTROL_TIME_HOUR,
	TYPE_GUI_CONTROL_TIME_MIN,
	TYPE_GUI_CONTROL_IMAGE_9SLICE,
    TYPE_GUI_CONTROL_END
} TYPE_GUI_CONTROL;


/*
**UI界面的排版
*/
typedef enum {
	TYPE_GUI_LAYOUT_PANNEL,
	TYPE_GUI_LAYOUT_LIST,
	TYPE_GUI_LAYOUT_SCROLL,
	TYPE_GUI_LAYOUT_GRID,   //宫格
    TYPE_GUI_LAYOUT_PAGE,
    TYPE_GUI_LAYOUT_CELLULAR,
    TYPE_GUI_LAYOUT_APPLE_CELLULAR,//完全模拟苹果的蜂窝
    TYPE_GUI_LAYOUT_LOOP,
    TYPE_GUI_LAYOUT_RING, //轮盘
    TYPE_GUI_LAYOUT_FLOW,
    // 废弃 TYPE_GUI_LAYOUT_RING_CENTER,
    TYPE_GUI_LAYOUT_CARD,
    TYPE_GUI_LAYOUT_MATRIX, //矩阵模式
} TYPE_GUI_LAYOUT;


typedef enum {
    TYPE_SWIPE_EFFECT_NONE,         // 平移
    TYPE_SWIPE_EFFECT_ZOOM_IN,      // 平移+放大
    TYPE_SWIPE_EFFECT_ZOOM_OUT,     // 平移+缩小
    TYPE_SWIPE_EFFECT_ZOOM_CIN,     // 中心点放大
    TYPE_SWIPE_EFFECT_ZOOM_COUT,    // 中心点缩小
    TYPE_SWIPE_EFFECT_COVER,        // 覆盖
}TYPE_SWIPE_EFFECT;

#endif

