#include "app_window_moreinfo_kaleidoscope_layout.h"
#include "application_config_app_info.h"
#include "picture.h"

#define ADD_KALEIDOSCOPE_APP(u_name, l_name)    \
	{                                           \
		.id = APP_INFO_ID_##u_name,             \
		.picture = &pic_app_##l_name##_88_info, \
	}

const gui_kaleidoscope_app_struct g_kaleidoscope_app[KALEIDOSCOPE_APP_TOTAL] =
	{
		ADD_KALEIDOSCOPE_APP(SPORT, sport_outdoor),
		ADD_KALEIDOSCOPE_APP(SLEEP, sleep),
		ADD_KALEIDOSCOPE_APP(O2, O2),
		ADD_KALEIDOSCOPE_APP(QR_PUSH, qr_push),	// (HOME, home),
		ADD_KALEIDOSCOPE_APP(BLOOD, BP),//1
		ADD_KALEIDOSCOPE_APP(HR, hr),
		ADD_KALEIDOSCOPE_APP(SIRI, siri),
		ADD_KALEIDOSCOPE_APP(MESSAGE, message),

		ADD_KALEIDOSCOPE_APP(STEP, steps),
		ADD_KALEIDOSCOPE_APP(CLACULATOR, calc),
		ADD_KALEIDOSCOPE_APP(BREATHE, breath),
		ADD_KALEIDOSCOPE_APP(STOPWATCH, stopwatch),
		ADD_KALEIDOSCOPE_APP(COUNTER, counter),
		ADD_KALEIDOSCOPE_APP(CALL, telephone),
		ADD_KALEIDOSCOPE_APP(WATCHFACE, watchface),
		ADD_KALEIDOSCOPE_APP(FIND, findphone),

		ADD_KALEIDOSCOPE_APP(CALENDAR, calendar),
		ADD_KALEIDOSCOPE_APP(ABOUT, about),
		ADD_KALEIDOSCOPE_APP(PHOTO, photograph),
		ADD_KALEIDOSCOPE_APP(SETTING, setting),
		ADD_KALEIDOSCOPE_APP(QR, QR_code),
		ADD_KALEIDOSCOPE_APP(RESTORE, restore),
		ADD_KALEIDOSCOPE_APP(WEATHER, weather),
		ADD_KALEIDOSCOPE_APP(GAME, game),//1
		ADD_KALEIDOSCOPE_APP(SHUTDOWN, shutdown),//1

//        ADD_KALEIDOSCOPE_APP(PHOTO, photograph),
//        ADD_KALEIDOSCOPE_APP(MESSAGE, message),
//        ADD_KALEIDOSCOPE_APP(LANGUAGE, style),
//        ADD_KALEIDOSCOPE_APP(LANGUAGE, sos),
//        ADD_KALEIDOSCOPE_APP(LANGUAGE, language),
//        ADD_KALEIDOSCOPE_APP(LANGUAGE, language),

};

const geometry_point gui_kaleidoscope_position_list[] =
	{
		{
			.x = LCD_SIZE_HALF_WIDTH,
			.y = LCD_SIZE_HALF_HEIGHT - (LCD_SIZE_HALF_HEIGHT + KALEIDOSCOPE_MAX_WIDTH),
		},
		{
			.x = LCD_SIZE_HALF_WIDTH + SIN_22_5 * (LCD_SIZE_HALF_HEIGHT + KALEIDOSCOPE_MAX_WIDTH),
			.y = LCD_SIZE_HALF_HEIGHT - COS_22_5 * (LCD_SIZE_HALF_HEIGHT + KALEIDOSCOPE_MAX_WIDTH),
		},
		{
			.x = LCD_SIZE_HALF_WIDTH + SIN_45_0 * (LCD_SIZE_HALF_HEIGHT + KALEIDOSCOPE_MAX_WIDTH),
			.y = LCD_SIZE_HALF_HEIGHT - COS_45_0 * (LCD_SIZE_HALF_HEIGHT + KALEIDOSCOPE_MAX_WIDTH),
		},
		{
			.x = LCD_SIZE_HALF_WIDTH + SIN_67_5 * (LCD_SIZE_HALF_HEIGHT + KALEIDOSCOPE_MAX_WIDTH),
			.y = LCD_SIZE_HALF_HEIGHT - COS_67_5 * (LCD_SIZE_HALF_HEIGHT + KALEIDOSCOPE_MAX_WIDTH),
		},

		{
			.x = LCD_SIZE_HALF_WIDTH + (LCD_SIZE_HALF_HEIGHT + KALEIDOSCOPE_MAX_WIDTH),
			.y = LCD_SIZE_HALF_HEIGHT,
		},
		{
			.x = LCD_SIZE_HALF_WIDTH + SIN_22_5 * (LCD_SIZE_HALF_HEIGHT + KALEIDOSCOPE_MAX_WIDTH),
			.y = LCD_SIZE_HALF_HEIGHT + COS_22_5 * (LCD_SIZE_HALF_HEIGHT + KALEIDOSCOPE_MAX_WIDTH),
		},
		{
			.x = LCD_SIZE_HALF_WIDTH + COS_45_0 * (LCD_SIZE_HALF_HEIGHT + KALEIDOSCOPE_MAX_WIDTH),
			.y = LCD_SIZE_HALF_HEIGHT + SIN_45_0 * (LCD_SIZE_HALF_HEIGHT + KALEIDOSCOPE_MAX_WIDTH),
		},
		{
			.x = LCD_SIZE_HALF_WIDTH + SIN_67_5 * (LCD_SIZE_HALF_HEIGHT + KALEIDOSCOPE_MAX_WIDTH),
			.y = LCD_SIZE_HALF_HEIGHT + COS_67_5 * (LCD_SIZE_HALF_HEIGHT + KALEIDOSCOPE_MAX_WIDTH),
		},

		{
			.x = LCD_SIZE_HALF_WIDTH,
			.y = LCD_SIZE_HALF_HEIGHT + (LCD_SIZE_HALF_HEIGHT + KALEIDOSCOPE_MAX_WIDTH),
		},
		{
			.x = LCD_SIZE_HALF_WIDTH - SIN_22_5 * (LCD_SIZE_HALF_HEIGHT + KALEIDOSCOPE_MAX_WIDTH),
			.y = LCD_SIZE_HALF_HEIGHT + COS_22_5 * (LCD_SIZE_HALF_HEIGHT + KALEIDOSCOPE_MAX_WIDTH),
		},
		{
			.x = LCD_SIZE_HALF_WIDTH - SIN_45_0 * (LCD_SIZE_HALF_HEIGHT + KALEIDOSCOPE_MAX_WIDTH),
			.y = LCD_SIZE_HALF_HEIGHT + COS_45_0 * (LCD_SIZE_HALF_HEIGHT + KALEIDOSCOPE_MAX_WIDTH),
		},
		{
			.x = LCD_SIZE_HALF_WIDTH - SIN_67_5 * (LCD_SIZE_HALF_HEIGHT + KALEIDOSCOPE_MAX_WIDTH),
			.y = LCD_SIZE_HALF_HEIGHT + COS_67_5 * (LCD_SIZE_HALF_HEIGHT + KALEIDOSCOPE_MAX_WIDTH),
		},

		{
			.x = LCD_SIZE_HALF_WIDTH - (LCD_SIZE_HALF_HEIGHT + KALEIDOSCOPE_MAX_WIDTH),
			.y = LCD_SIZE_HALF_HEIGHT,
		},
		{
			.x = LCD_SIZE_HALF_WIDTH - SIN_22_5 * (LCD_SIZE_HALF_HEIGHT + KALEIDOSCOPE_MAX_WIDTH),
			.y = LCD_SIZE_HALF_HEIGHT - COS_22_5 * (LCD_SIZE_HALF_HEIGHT + KALEIDOSCOPE_MAX_WIDTH),
		},
		{
			.x = LCD_SIZE_HALF_WIDTH - COS_45_0 * (LCD_SIZE_HALF_HEIGHT + KALEIDOSCOPE_MAX_WIDTH),
			.y = LCD_SIZE_HALF_HEIGHT - SIN_45_0 * (LCD_SIZE_HALF_HEIGHT + KALEIDOSCOPE_MAX_WIDTH),
		},
		{
			.x = LCD_SIZE_HALF_WIDTH - SIN_67_5 * (LCD_SIZE_HALF_HEIGHT + KALEIDOSCOPE_MAX_WIDTH),
			.y = LCD_SIZE_HALF_HEIGHT - COS_67_5 * (LCD_SIZE_HALF_HEIGHT + KALEIDOSCOPE_MAX_WIDTH),
		},
};

const gui_screen_struct gui_screen_moreinfo_kaleidoscope =
	{
		.type = TYPE_GUI_LAYOUT_PANNEL,
		.order = 0,
};
