#ifndef __SPORT_TYPE_DEF__
#define __SPORT_TYPE_DEF__


typedef enum
{
    MIX_SPORT_NULL = 0,
    
    MIX_SPORT_BREATHE = 1,//呼吸
    MIX_SPORT_CYCLING = 2,//骑车或室外骑车
    MIX_SPORT_CYCLING_INDOOR = 3,//室内骑车
    MIX_SPORT_RUNNING_MACHINE = 4,//跑步机或室内跑步
    MIX_SPORT_RUN = 5,//跑步或室外跑步
    MIX_SPORT_SWIM = 6,//游泳
    MIX_SPORT_WALK = 7,//走路
    MIX_SPORT_WEIGHT = 8,//举重
    MIX_SPORT_YOGA = 9,//瑜咖
    MIX_SPORT_BADMINTON = 10,//羽毛球
    MIX_SPORT_BASKETBALL = 11,//蓝球
    MIX_SPORT_SKIP = 12,//跳绳
    MIX_SPORT_FREE_EXERCISE = 13,//自由锻炼
    MIX_SPORT_FOOTBALL = 14,//足球
    MIX_SPORT_CLIMBING = 15,//爬山
    MIX_SPORT_PINGPONG = 16,//乒乓球
    MIX_SPORT_BOWLING = 17,//保龄球
    MIX_SPORT_OPENWATER = 18,//开放水域
    MIX_SPORT_DANCE = 19,//跳舞
    MIX_SPORT_DUMBBELL = 20,//哑铃
    MIX_SPORT_HULAHOOP = 21,//转呼啦圈
    MIX_SPORT_STAIRSOVEMENT = 22,//楼梯运动
    MIX_SPORT_TREADMILLS = 23,//踏步机
    MIX_SPORT_TRIATHLON = 24,//铁人三项
    MIX_SPORT_SITUP = 25,//仰卧起坐
    MIX_SPORT_SKIING = 26,//滑雪
    MIX_SPORT_BILLIARDS = 27,//台球
    MIX_SPORT_ELLIPTICALMACHINE = 28,//椭圆机
    MIX_SPORT_CROSSCOUNTRYRACE = 29,//越野跑
    MIX_SPORT_AEROBICS = 30,//健美操
    MIX_SPORT_PILATES = 31,//普拉提
    MIX_SPORT_SHUTTLECOCKKICKING = 32,//踢毽子
    MIX_SPORT_ROTATE = 33,//旋转
    MIX_SPORT_WALKINGMACHINE = 34,// 走步机
    MIX_SPORT_CRICKET = 35,     //板球
    MIX_SPORT_VOLLEYBALL = 36,  //排球
    MIX_SPORT_JUDO = 37,        //柔道
    MIX_SPORT_KARETE = 38,      //空手道
    MIX_SPORT_TAEKWONDO = 39,   //跆拳道
    MIX_SPORT_ROCKCLIMBING = 40,//攀岩
    MIX_SPORT_HOCKEY = 41,      //曲棍球
    MIX_SPORT_WRESTING = 42,    //摔跤
    MIX_SPORT_ROWING = 43,      //赛艇
    MIX_SPORT_MOUNTAIN_BIKING = 44, //山地自行车 /山地摩托车
    MIX_SPORT_MOTOCROSS = 45,   //越野摩托车
    MIX_SPORT_ROWING_MACHINE = 46,   //划船机
    MIX_SPORT_BALLET = 47,      //芭蕾舞
    MIX_SPORT_STREET_DANCE = 48, //街舞
    MIX_SPORT_JAZZ = 49,        //爵士
    MIX_SPORT_POLE_DANCE = 50,  //钢管舞
    MIX_SPORT_FOLK_DANCE = 51,  //民族舞
    MIX_SPORT_BREAK_DANCE = 52, //霹雳舞
    MIX_SPORT_MARTIAL_ARTS = 53, //武术
    MIX_SPORT_TAI_CAI = 54,     //太极
    MIX_SPORT_JUJITSU = 55,     //柔术
    MIX_SPORT_KENDO = 56,       //剑道
    MIX_SPORT_BEACH_FOOTBALL = 57, //沙滩足球
    MIX_SPORT_BEACH_VOLLEYBALL = 58, //沙滩排球
    MIX_SPORT_BASEBALL = 59,        //棒球
    MIX_SPORT_SOFTBALL = 60,    //垒球
    MIX_SPORT_WATER_POLO = 61,  //水球
    MIX_SPORT_CROSSCOUNTRYSKIING = 62,//越野滑雪
    MIX_SPORT_OUTDOOR_SKATING = 63, //户外滑冰
    MIX_SPORT_SLED = 64,        //雪橇
    MIX_SPORT_SNOWMOBILE = 65,  //雪地摩托
    MIX_SPORT_FRISBEE = 66,     //飞盘
    MIX_SPORT_DARTS = 67,       //飞镖
    MIX_SPORT_KITE_FLYING = 68, //风筝
    MIX_SPORT_AIR_WALKER = 69, //空中助行器
    MIX_SPORT_ROLLER_SKATING = 70, //轮滑
    MIX_SPORT_ARCHERY = 71,         //射箭
    MIX_SPORT_EQUESTRIAN = 72,      //马术
    MIX_SPORT_DRIVE = 73,           //驾驶
    MIX_SPORT_CLIMB_STAIRS = 74,   //爬楼梯
    MIX_SPORT_SQUASH =75,           //壁球
    MIX_SPORT_CULING = 76,          //冰壶
    MIX_SPORT_LINE_SKATING = 77,    //排队滑冰
    MIX_SPORT_SAILING  = 78,        //帆船
    MIX_SPORT_WATER_SPORTS = 79,    //水上运动
    MIX_SPORT_PADDLE_BOARDING = 80, //单桨冲浪
    MIX_SPORT_WATER_SKIING = 81,    //划水
    MIX_SPORT_KAYAKING = 82,        //皮划艇
    MIX_SPORT_RAFTING = 83,         //漂流
    MIX_SPORT_DRAGON_BOAT = 84,          //龙舟
    MIX_SPORT_POWERBOATING = 85,    //摩托艇
    MIX_SPORT_FINSWIMMING = 86,     //噗游泳
    MIX_SPORT_ARTISTIC_SWIMMING = 87, //花样游泳
    MIX_SPORT_KITESURFNG  = 88,     //风筝冲浪
    MIX_SPORT_OPEN_SWIM = 89,       //公开游泳
    MIX_SPORT_SKATRBOARDING = 90,   //滑板
    MIX_SPORT_PARKOUT = 91,         //跑酷
    MIX_SPORT_ATV = 92,             //沙滩车
    MIX_SPORT_PARAGLIDING = 93,     //滑翔伞
    MIX_SPORT_OUTDOOR_RUNNING = 94, //户外跑步
    MIX_SPORT_ON_FOOT = 95,         //徒步
    MIX_SPORT_KABADDI = 96,         //卡巴迪
    MIX_SPORT_CORE_TRAINING = 97,   //核心训练
    MIX_SPORT_FLEXIBILITY = 98,     //柔韧性
    MIX_SPORT_GYMNASTICS = 99,      //体操
    MIX_SPORT_STRETCHING = 100,     //伸展运动
    MIX_SPORT_STRENGTH  = 101,      //力量
    MIX_SPORT_CROSS_TRAINING = 102,     //交叉训练
    MIX_SPORT_PHYSICAL_TRAINING = 103,  //体能训练
    MIX_SPORT_BARBELL = 104,        //杠铃
    MIX_SPORT_DEADLIFT = 105,       //硬拉
    MIX_SPORT_UPPER_BODY = 106,     //上半身
    MIX_SPORT_FUNCTIONALL_TRAINING = 107, //功能训练
    MIX_SPORT_BURPEE = 108,         //波比
    MIX_SPORT_BACK_EXERCISE = 109,  //背部训练
    MIX_SPORT_LOWER_BODY = 110,     //下半身
    MIX_SPORT_ABS = 111,            //腹肌
    MIX_SPORT_HIIT = 112,           //燃脂
    MIX_SPORT_LNDOOR_WALKING = 113, //室内步行
    MIX_SPORT_SQUARE_DANCING = 114, //广场舞
    MIX_SPORT_BELLY_DANCE = 115,    //肚皮舞
    MIX_SPORT_ZUMBA = 116,          //尊巴舞
    MIX_SPORT_LATIN_DANCE = 117,    //拉丁舞
    MIX_SPORT_JAZZ_DANCE = 118,     //爵士舞
    MIX_SPORT_BOXING = 119,         //拳击
    MIX_SPORT_MUAY_THAI = 120,      //泰拳
    MIX_SPORT_FENCING = 121,        //击剑
    MIX_SPORT_HANDBALL = 122,       //手球
    MIX_SPORT_SHUTTLECOCK = 123,    //毽球
    MIX_SPORT_SPEAK_TAKRAW = 124,   //藤球
    MIX_SPORT_LCE_SKATING = 125,    //滑冰
    MIX_SPORT_LCE_HOCKEY = 126,     //冰球
    MIX_SPORT_BOBSLEIGH = 127,      //有舵雪橇
    MIX_SPORT_TUG_OF_WAR = 128,     //拔河
    MIX_SPORT_HULA_HOOP = 129,      //呼啦圈
    MIX_SPORT_HOUSE_RIDING = 130,   //骑马
    MIX_SPORT_FISHING = 131,        //钓鱼
    MIX_SPORT_ATHLETICS = 132,      //田径
    MIX_SPORT_AUTO_RACING = 133,    //赛车
    MIX_SPORT_GOALBALL = 134,       //门球
    MIX_SPORT_GOLF = 135,           //高尔夫
    MIX_SPORT_HURDLE = 136,         //跨栏
    MIX_SPORT_RUGBY = 137,          //橄榄球
    MIX_SPORT_BIATHION_WINTER = 138,//冬季两项
    MIX_SPORT_BOOSTER = 139,        //助推器
    MIX_SPORT_TENNIS = 140,     //网球
    MIX_SPORT_MAX
}MIX_SPORT_TYPE;

#endif

