#ifndef __APP_WINDOW_LOCALMUSIC_LAYOUT_H__
#define __APP_WINDOW_LOCALMUSIC_LAYOUT_H__

#include "feature_all.h"
#include "gui_core_all.h"

#define LOCALMUSIC_NAME_X    0
#define LOCALMUSIC_NAME_Y    45
#define LOCALMUSIC_NAME_H    24

#define LOCALMUSIC_PLAY_X    80
#define LOCALMUSIC_PLAY_Y    99
#define LOCALMUSIC_NEXT_X    171
#define LOCALMUSIC_NEXT_Y    85
#define LOCALMUSIC_PREV_X    10
#define LOCALMUSIC_PREV_Y    85
#define LOCALMUSIC_ANI_X     11
#define LOCALMUSIC_ANI_Y     210
#define LOCALMUSIC_ANI_H     56

enum
{
    LOCALMUSIC_LAYOUT_ID_BG = 100,
    LOCALMUSIC_LAYOUT_ID_TITLE_NAME,
    LOCALMUSIC_LAYOUT_ID_TITLE_TIME,
    LOCALMUSIC_LAYOUT_ID_BTSTA,
    LOCALMUSIC_LAYOUT_ID_PLAY,
    LOCALMUSIC_LAYOUT_ID_NAME,
    LOCALMUSIC_LAYOUT_ID_YL,
    LOCALMUSIC_LAYOUT_ID_ANI,

    LOCALMUSIC_LAYOUT_VOLUP_ID,
    LOCALMUSIC_LAYOUT_VOLBG_ID,
    LOCALMUSIC_LAYOUT_VOLIND_ID,
    LOCALMUSIC_LAYOUT_VOLDN_ID,
};

extern const gui_screen_struct gui_screen_localmusic;

#endif

